algoritmo "10)exercicio"
// Função :
// Autor :
// Data : 05/05/2021
// Seção de Declarações 
var
Al,La:real

inicio
Escreval("Qual altura da parede que deseja pintar?")
Leia (Al)
Escreval("Qual largura da mesma parede que deseja pintar?")
Leia (La)
Escreval("A área dessa parede é de ",Al*La,"m²")
Escreval("Você precisará de ",(Al*La)/2," Litros de tinta para pintar toda essa área.")

// Seção de Comandos 
fimalgoritmo
