algoritmo "11_exercicio"
// Data : 05/05/2021
// Seção de Declarações 

var
Na,Nb,Nc: real
inicio
Escreval("Informar número para representar letra 'A' na equação de 2ºgrau")
Leia (Na)
Escreval("Informar número para representar letra 'B' na equação de 2ºgrau")
Leia (Nb)
Escreval("Informar número para representar letra 'C' na equação de 2º grau")
Leia (Nc)
Escreval("Resolvendo a equação a seguir:",Na,"x²",Nb,"x",Nc)
Escreval("Temos que delta é ",(Nb^2)-4*Na*Nc)

fimalgoritmo
