algoritmo "12)exercicio"
// Função :
// Autor :
// Data : 05/05/2021
// Seção de Declarações 
var
ValProd: Real
inicio
Escreval("Sistema para produtos em promoção de 5%")
Escreval("Digite o valor do produto que está na promoção R$ ")
Leia (ValProd)
Escreval("O Valor do desconto de 5% é de R$ ",ValProd*0.05)
Escreval("O valor do produto com desconto será R$",ValProd*0.95)
fimalgoritmo
