algoritmo "15)exercicio"
// Função :
// Autor :
// Data : 05/05/2021
// Seção de Declarações 
var
DiaTrab,S: real

inicio
Escreval("Qual número de dias trabalhados em um período de um mês?")
Leia (DiaTrab)
S<-(DiaTrab*25*8)
Escreval("A jornada de trabalho é de 8 horas por dia e ganha R$25,00 por hora trabalhada")
Escreval("A quantidade de dias trabalhados é de ",DiaTrab)
Escreval("e o salário correspondete a esses dias trabalhados é de",S)

// Seção de Comandos 
fimalgoritmo
