algoritmo "21_exercicio"
// Seção de Declarações 

var
   A:inteiro
   F:real
inicio
      Escreval("Para descobrir se o ano que vc escolher é bissexto digite qualquer ano: ")
      Leia (A)
      F<-A/4
          //nao consigo aplicar a logica aqui por enquanto
            se(F%4=0)entao
              Escreval("O ano ",A," é bissexto")
            senao
                 Escreval("Ano ",A," não é bissexto")
            fimse
fimalgoritmo
