algoritmo "3)exercicio"
// Função :
// Autor :
// Data : 05/05/2021
// Seção de Declarações 
var
Nome: caractere
Salario: real

inicio
      Escreval("Olá, qual nome do funcionário?")
      Leia (Nome)
       Escreval("Qual salário dessa pessoa apenas em números?")
      Leia (Salario)
      Escreval("Nome do funcionario é ",Nome)
      Escreval("O salário desse funcionário é de R$ ",Salario)
fimalgoritmo
