algoritmo "8_exercicio"
// Seção de Declarações 

var
   N1:Real
inicio
      Escreval("Informe um valor em metros e retornaremos o valor referido em outros medidas")
      Leia (N1)
      Escreval("O valor digitado foi",N1," e a conversão em kilometros será ",N1/1000, "km")
      Escreval("A conversão em centímetros será de ",N1/100, "cm")
      Escreval("A conversão em milímetros será de ",N1/1000, "mm")
fimalgoritmo
